import numpy as np

HIP_CENTER  = 0

HIP_LEFT    = 1
FEMUR_LEFT  = 2
TIBIA_LEFT  = 3
FOOT_LEFT   = 4
TOES_LEFT   = 5

HIP_RIGHT   = 6
FEMUR_RIGHT = 7
TIBIA_RIGHT = 8
FOOT_RIGHT  = 9
TOES_RIGHT  = 10

BACK_LOWER  = 11
BACK_UPPER  = 12
THORAX      = 13
NECK_LOWER  = 14
NECK_UPPER  = 15
HEAD        = 16

CLAVICLE_LEFT = 17
HUMEROUS_LEFT = 18
RADIUS_LEFT = 19
WRIST_LEFT = 20
HAND_LEFT = 21
FINGERS_LEFT = 22
THUMB_LEFT = 23

CLAVICLE_RIGHT = 24
HUMEROUS_RIGHT = 25
RADIUS_RIGHT = 26
WRIST_RIGHT = 27
HAND_RIGHT = 28
FINGERS_RIGHT = 29
THUMB_RIGHT = 30

LEG_LEFT = np.array([HIP_LEFT, FEMUR_LEFT,TIBIA_LEFT,FOOT_LEFT])#,TOES_LEFT]
LEG_RIGHT = np.array([HIP_RIGHT, FEMUR_RIGHT, TIBIA_RIGHT, FOOT_RIGHT])#, TOES_RIGHT]
ARM_LEFT  = np.array([ CLAVICLE_LEFT, HUMEROUS_LEFT, RADIUS_LEFT, WRIST_LEFT, HAND_LEFT])# , FINGERS_LEFT, THUMB_LEFT]
ARM_RIGHT = np.array([ CLAVICLE_RIGHT, HUMEROUS_RIGHT, RADIUS_RIGHT, WRIST_RIGHT, HAND_RIGHT])#, FINGERS_RIGHT, THUMB_RIGHT]
TORSO = np.array([HIP_CENTER,BACK_LOWER, BACK_UPPER, THORAX,NECK_LOWER, NECK_UPPER, HEAD])

FULL_BODY = np.array(range(0,31))
